<a href="https://colab.research.google.com/github/moyixinqing/CSE6040x/blob/master/Numpy_Multiply.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy Multiply**

In [4]:
import numpy as np

**2D Array**

In [12]:
a=np.array([[1,2],
            [3,4]])

b=np.array([[11,12],
            [13,14]])


**np.dot**

sum(a[i, :]* b[:, j])]

*  If both a and b are 1-D arrays, it is inner product of vectors 
*  If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.
*  If either a or b is 0-D (scalar), it is equivalent to multiply and using numpy.multiply(a, b) or a * b is preferred.






In [13]:
np.dot(a,b)

array([[37, 40],
       [85, 92]])

**np.inner**

sum(a[i, :]* b[j, :])]

Ordinary inner product of vectors for 1-D arrays (without complex conjugation), in higher dimensions a sum product over the last axes.

In [27]:
np.inner(a,b)

array([[35, 41],
       [81, 95]])

relationship between dot and inner


In [19]:
np.allclose(np.dot(a,b),np.inner(a,b.T))

True

In [20]:
np.allclose(np.dot(a,b.T),np.inner(a,b))

True

**np.multiply**

or a * b 

element-wise multiplication


In [16]:
np.multiply(a,b)

array([[11, 24],
       [39, 56]])

In [23]:
np.allclose(np.multiply(a,b), a*b)

True

**np.malmul**

or a@b matrix Multiplicatin

matmul differs from dot in two important ways:

1.   Multiplication by scalars is not allowed, use * instead.
2.   Stacks of matrices are broadcast together as if the matrices were elements, respecting the signature (n,k),(k,m)->(n,m)




In [25]:
np.matmul(a,b)

array([[37, 40],
       [85, 92]])

In [26]:
np.allclose(np.matmul(a,b), a@b)

True

**3D Array**


In [5]:
a = np.random.rand(8,13,13)
b = np.random.rand(8,13,13)

In [11]:
np.allclose(np.einsum('ijk,ijk->ijk', a,b), a*b)        # True 

True

In [7]:
np.allclose(np.einsum('ijk,ikl->ijl', a,b), a@b)        # True

True

In [9]:
np.allclose(np.einsum('ijk,lkm->ijlm',a,b), a.dot(b))   # True

True